package com.shogek.spinoza

const val CONVERSATION_ID = "CONVERSATION_ID"
const val NO_CONVERSATION_ID = -1
const val CONTACT_ID = "CONTACT_ID"
const val SMS_SENT_PENDING_INTENT = "SMS_SENT_PENDING_INTENT"
const val PARAM_PICK_CONTACT = "PARAM_PICK_CONTACT"